#!/bin/zsh

cd src
echo "Building Xpl.g grammar"
echo "----------------------------------------------------------------"
java org.antlr.Tool Xpl.g
echo
echo "Building SemanticAnalysis.g grammar"
echo "----------------------------------------------------------------"
java org.antlr.Tool SemanticAnalysis.g
echo
echo "Building CodeGeneration.g grammar"
echo "----------------------------------------------------------------"
java org.antlr.Tool CodeGeneration.g
echo
echo "Compiling Java source files"
echo "----------------------------------------------------------------"
javac *.java -d ../bin
if [[ $? = 1 ]]; then
    exit
fi
echo
cd ..

cd bin
echo "Running the bytecode generator"
echo "----------------------------------------------------------------"
java Xpl test.xpl test.class
echo
echo "Running the resulting output"
echo "----------------------------------------------------------------"
java test
echo
cd ..
